import React from 'react'
import Head from 'next/head'
import { Home } from '../pages/Home'
import { IHomeProps } from '../../@types/IHomeProps'
import styles from './styles.module.css'

export const HomeContainer = (props: IHomeProps) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Home {...props} />
      </main>
    </>
  )
}
