import React from 'react'
import Head from 'next/head'
import { Home } from '../pages/Home'
import { IHomeProps } from '../../@types/IHomeProps'

export const HomeContainer = ({
  fictionBooks,
  dramaBooks,
  fantasyBooks,
}: IHomeProps) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Home
          fictionBooks={fictionBooks}
          dramaBooks={dramaBooks}
          fantasyBooks={fantasyBooks}
        />
      </div>
    </>
  )
}
