import { GetStaticProps } from 'next'
import Head from 'next/head'
import React from 'react'
import * as C from '../styles/home'
import Slider from '../components/Slider'
import { SwiperSlide, SwiperProps } from 'swiper/react'
import { Pagination } from "swiper";
import {NEW_BOOKS, SEARCH_BOOKS_ID,SEARCH_BOOKS_GENRES} from '../Api'
import { Book } from '../Types/Books'
import SliderBooks from '../components/SliderBooks'

interface Props {
  book?: Book
  fictionBooks: {
    kind: string
    totalItems: number
    items: Book[]
  }
  dramaBooks: {
    kind: string
    totalItems: number
    items: Book[]
  },
  fantasyBooks: {
    kind: string
    totalItems: number
    items: Book[]
  }
}




export default function Home({fictionBooks,dramaBooks,fantasyBooks}:Props) {
  console.log(dramaBooks)
    const settings : SwiperProps = {
      //config swiper slide
      slidesPerView: 1,
      pagination:{clickable:true}
    }
    const booksSettings : SwiperProps = {
      slidesPerView: 3,
      spaceBetween:100,
      navigation:true,
      pagination: { clickable: true }
    }
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <C.Container>
        <section className="sliderPresentation">
          <Slider settings={settings}>
            <SwiperSlide>
              <img src="/images/prop1.webp" alt="" />
            </SwiperSlide>
            <SwiperSlide>
              <img src="/images/prop2.png" alt="" />
            </SwiperSlide>
            <SwiperSlide>
              <img src="/images/prop3.webp" alt="" />
            </SwiperSlide>
          </Slider>
        </section>
        {fictionBooks && (
          <section className="newBooks">
            <h1 className="title">Ficção</h1>
            <SliderBooks books={fictionBooks} />
          </section>
        )}
        {dramaBooks && (
          <section className="dramaBooks">
            <h1 className="title">Dramas</h1>
            <SliderBooks books={dramaBooks} />
          </section>
        )}
        {fantasyBooks && (
          <section className="fantasyBooks">
            <h1 className="title">Fatasia</h1>
            <SliderBooks books={fantasyBooks} />
          </section>
        )}
      </C.Container>
    </>
  )
}

export const getStaticProps:GetStaticProps = async () =>{
  const fictionBooks = await SEARCH_BOOKS_GENRES('fiction')
  const dramaBooks = await SEARCH_BOOKS_GENRES('drama')
  const fantasyBooks = await SEARCH_BOOKS_GENRES('fantasy')
  return{
    props:{
      fictionBooks,
      dramaBooks,
      fantasyBooks
    },
    revalidate: 60 * 60
  }
}


